# Generated by Django 3.1.3 on 2020-11-04 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='voter',
            field=models.ManyToManyField(blank=True, null=True, related_name='voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
